[tool.poetry]
name = "vr_address_tools"
version = "1.4.0"
description = "Tools for converting a Skyrim SSE/Fallout 4 skse/F4SE mod to Skyrim/Fallout VR"
authors = ["Alan D. Tse <alandtse@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
robotpy-cppheaderparser = ">=5.0.15"
pandas = "^1.4.2"
python-semantic-release = ">=7.32.1"
pcpp = "^1.30"
aiofiles = "^24"
aiocsv = "^1.2.5"
orjson = "^3.8.8"

[tool.poetry.group.dev.dependencies]
black = ">=21.9b0"
mypy = ">=0.950"
pytest = "^8.3.1"
xdoctest = "^1.1.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = 'pyproject.toml:version'
upload_to_pypi = false
upload_to_release = false
changelog_sections = "feature,fix,breaking,documentation,performance,refactor"
build_command = ""
branch = "main"
commit_subject = "[skip ci] {version}"
